Working devcontainer for building and running choco in Docker on Linux
chocolate-doom/chocolate-doom pull request #1442
Opened 2022-02-09 03:55 UTC by fsufitch

2022-02-09 18:00 UTC, fragglet requested changes

2022-02-09 19:47 UTC, fsufitch commented on .devcontainer/Dockerfile
> +ARG choco_apt_dependencies="gcc make libsdl2-dev libsdl2-net-dev libsdl2-mixer-dev"
Absolutely. Does Choco gracefully downgrade if it's built with libpng and libpng isn't available later, though?

2022-02-09 19:48 UTC, fsufitch commented on .devcontainer/devcontainer.json
> +	"name": "Existing Dockerfile",
Yeah, it should, this was just the default. I'm doing a few more polish passes and removing placeholders, pointless "guide" comments and making values more significant/specific is part of it.

2022-02-10 03:30 UTC, fsufitch commented on .devcontainer/devcontainer.json
> +	"name": "Existing Dockerfile",
Fixed it.

2022-02-10 03:31 UTC, fsufitch commented on .devcontainer/Dockerfile
> +ARG choco_apt_dependencies="gcc make libsdl2-dev libsdl2-net-dev libsdl2-mixer-dev"
Fixed.

2022-02-12 08:11 UTC, fragglet approved these changes

2022-02-12 08:11 UTC, merged