medusa bug indicator instead of random memory access
chocolate-doom/chocolate-doom pull request #1498
Opened 2022-08-25 22:40 UTC by kgsws

This should indicate "medusa" columns instead of randomly accessing memory, slowing down, and potentially crashing the game.
(You can even add an option to fix this bug properly.)

2022-08-26 12:50 UTC, turol requested changes
I'm not familiar enough with the renderer to say this is 100% correct. Someone else?

Does it emulate how genuine medusa looks? Have you tested this with Valgrind/ASAN to make sure it's complete?

2022-08-26 12:50 UTC, turol commented on src/doom/r_segs.c
> +extern int *texturecompositesize;
Don't put `extern` in a .c file. Put it in an .h file where it will also reach the actual definition. This way the compiler will check it's correct.

2022-08-26 12:50 UTC, turol commented on src/doom/r_segs.c
> +boolean medusa_indicator(void *data, int texture)
If `data` is not modified it should be `const`.

2022-08-26 12:50 UTC, turol commented on src/doom/r_segs.c
> +#if 0
This should probably be a runtime configurable variable.

2022-08-26 12:50 UTC, turol commented on src/doom/r_segs.c
> +	    if(medusa_indicator((void*)col + 3, texnum))
Or maybe the runtime check belongs here?

2022-08-26 19:31 UTC, kgsws commented
Valgrind - no errors. That "#if 0" serves only as an example how to fix this properly, just for reference. Oh, and "medusa_ptr" is actually modified.

It will render entire texture using single color, cycling 0 to 255 (so the entire palette). But it will render it correctly. That is, it will render only original texture height and position.

I thought this is better than emulating medusa bug to give mappers indication that "something is wrong".
I can make it emulate medusa bug, but the code would be somewhat different. And since medusa bug is basically random, it won't ever look the same.

2022-08-29 12:20 UTC, turol commented
@fragglet What kind of options do we want here and what should be the default?

2023-06-09 14:17 UTC, closed without merging